# -*- coding: utf-8 -*-
"""deber1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_WlhPOmWzysA9_tQ_LPGAQdO-4NP4gK
"""

print("Producto de dos números")
print("Ingrese un número: ")
numero = float(input())
print("Ingrese otro número: ")
numero2 = float(input())
print(f"El producto es: {numero * numero2}")