# -*- coding: utf-8 -*-
"""operaciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18nQk5RUwoktFk40AW9da3WoBCpkc8IHN
"""

while(True):
  print("Calculadora: \n1.Suma \n2.Resta \n3.Multiplicación \n4.Division \n5.Salir")
  numero = float(input())
  if(numero == 1):
    print("Ingrese el primer número:")
    numero1 = float(input())
    print("Ingrese el segundo número:")
    numero2 = float(input())
    print(f"El resultado de la suma es: {numero1 + numero2}")
  if(numero == 2):
    print("Ingrese el primer número:")
    numero1 = float(input())
    print("Ingrese el segundo número:")
    numero2 = float(input())
    print(f"El resultado de la resta es: {numero1 - numero2}")
  if(numero == 3):
    print("Ingrese el primer número:")
    numero1 = float(input())
    print("Ingrese el segundo número:")
    numero2 = float(input())
    print(f"El resultado de la multiplicación es: {numero1 * numero2}")
  if(numero == 4):
    print("Ingrese el primer número:")
    numero1 = float(input())
    print("Ingrese el segundo número:")
    numero2 = float(input())
    print(f"El resultado de la división es: {numero1 / numero2}")
  if(numero == 5):
    print("Saliendo...")
    break